### ISSUE TITLE
What is the possibility of integrating other projects?

### ISSUE THREAD

**Issue by juandav** [juliandavidmr/rp#1]
link to repo: [Blueberry](https://github.com/gosukiwi/Blueberry)
link to repo [Guts](https://github.com/c9s/guts)

**Comment by juliandavidmr** [comment]
I didn't really know those two projects. I will have to rethink a part of the project, although there are many options that will make _rp_ different from the other languages. Then I will put more emphasis on them through issues - github. 

thanks @juandav

**Comment by juandav** [comment]
osom!!
